POST http://localhost:8080/api/transactions
Content-Type: application/json

{
  "selectedColumns": [
    "TRANSACTION_ID",
    "TRANSACTION_AMOUNT",
    "TRANSACTION_FEE",
    "TRANSACTION_ADDRESS",
    "TRANSACTION_COUNTRY",
    "TRANSACTION_APPROVAL_STATUS",
    "TRANSACTION_APPROVAL_DATE",
    "TRANSACTION_DATE",
    "TRANSACTION_STATUS",
    "TRANSACTION_CATEGORY",
    "SENDER_ACCOUNT_NUMBER",
    "SENDER_ACCOUNT_CURRENCY",
    "SENDER_ACCOUNT_CARD_NUMBER",
    "SENDER_ACCOUNT_CARD_TYPE",
    "SENDER_CUSTOMER_FULLNAME",
    "SENDER_CUSTOMER_FIRSTNAME",
    "SENDER_CUSTOMER_LASTNAME",
    "SENDER_CUSTOMER_AGE",
    "SENDER_CUSTOMER_RETIRED_IND",
    "SENDER_CUSTOMER_EMAIL",
    "SENDER_CUSTOMER_COUNTRY",
    "SENDER_CUSTOMER_POSTAL_CODE",
    "SENDER_CUSTOMER_PHONE_NUMBER",
    "RECIPIENT_ACCOUNT_NUMBER",
    "RECIPIENT_ACCOUNT_CURRENCY",
    "RECIPIENT_ACCOUNT_CARD_NUMBER",
    "RECIPIENT_ACCOUNT_CARD_TYPE",
    "RECIPIENT_CUSTOMER_FULLNAME",
    "RECIPIENT_CUSTOMER_FIRSTNAME",
    "RECIPIENT_CUSTOMER_LASTNAME",
    "RECIPIENT_CUSTOMER_AGE",
    "RECIPIENT_CUSTOMER_RETIRED_IND",
    "RECIPIENT_CUSTOMER_EMAIL",
    "RECIPIENT_CUSTOMER_COUNTRY",
    "RECIPIENT_CUSTOMER_POSTAL_CODE",
    "RECIPIENT_CUSTOMER_PHONE_NUMBER"
  ],
  "filters": [],
  "pageSize": 10
}

<> 01_all_fields_response.json